<?xml version="1.0" encoding="utf-8"?><Database Name="Legion" Class="LegionLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=acheron;Initial Catalog=Legion;Integrated Security=True" SettingsObjectName="Caesar.Properties.Settings" SettingsPropertyName="LegionConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.xspDeleteService" Method="xspDeleteService">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspDeleteServiceMethod" Method="xspDeleteServiceMethod">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspDeleteServiceSetting" Method="xspDeleteServiceSetting">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="serviceid" Type="System.Int32" DbType="Int" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspSetSettingById" Method="xspSetSettingById">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="value" Type="System.String" DbType="VarChar(1000)" />
    <ElementType Name="xspSetSettingByIdResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspSetSettingByKey" Method="xspSetSettingByKey">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="value" Type="System.String" DbType="VarChar(1000)" />
    <ElementType Name="xspSetSettingByKeyResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspGetSettingById" Method="xspGetSettingById">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="value" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspGetSettingByKey" Method="xspGetSettingByKey">
    <Parameter Name="key" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="value" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspDeleteApplication" Method="xspDeleteApplication">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspGetApplicationPermissions" Method="xspGetApplicationPermissions">
    <Parameter Name="applicationId" Type="System.Int32" DbType="Int" />
    <ElementType Name="xspGetApplicationPermissionsResult">
      <Column Name="MethodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspDeleteAllApplciationPermissions" Method="xspDeleteAllApplciationPermissions">
    <Parameter Name="applicationId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspCheckApplicationKeyForCollision" Method="xspCheckApplicationKeyForCollision">
    <Parameter Name="appKey" Type="System.String" DbType="Char(36)" />
    <Parameter Name="tfCollision" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <ElementType Name="xspCheckApplicationKeyForCollisionResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspGetServerStatus" Method="xspGetServerStatus">
    <ElementType Name="xspGetServerStatusResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="HostName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsAssemblyRefreshRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsCacheRefreshRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspAddApplicationPermission" Method="xspAddApplicationPermission">
    <Parameter Name="applicationId" Type="System.Int32" DbType="Int" />
    <Parameter Name="methodId" Type="System.Int32" DbType="Int" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <ElementType Name="xspAddApplicationPermissionResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspRevokeKey" Method="xspRevokeKey">
    <Parameter Name="applicationid" Type="System.Int32" DbType="Int" />
    <Parameter Name="key" Type="System.String" DbType="Char(36)" />
    <Parameter Name="resultcode" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspUpdateService" Method="xspUpdateService">
    <Parameter Name="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="serviceKey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="serviceDescription" Type="System.String" DbType="Char(36)" />
    <Parameter Name="serviceIPRange" Type="System.String" DbType="VarChar(31)" />
    <Parameter Name="serviceAssembly" Type="System.String" DbType="VarChar(31)" />
    <Parameter Name="serviceClass" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="restricted" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="public" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="logged" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspGetService" Method="xspGetService">
    <Parameter Name="serviceid" Type="System.Int32" DbType="Int" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <ElementType Name="xspGetServiceResult">
      <Column Name="ServiceKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssemblyName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ConsumerIPRange" Type="System.String" DbType="VarChar(31)" CanBeNull="true" />
      <Column Name="IsRestricted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLogged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspGetServices" Method="xspGetServices">
    <ElementType Name="xspGetServicesResult">
      <Column Name="ServiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssemblyName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ConsumerIPRange" Type="System.String" DbType="VarChar(31)" CanBeNull="true" />
      <Column Name="IsRestricted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLogged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspGetMethods" Method="xspGetMethods">
    <ElementType Name="xspGetMethodsResult">
      <Column Name="MethodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MethodKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MethodName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsMissing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRestricted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLogged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspGetServiceMethods" Method="xspGetServiceMethods">
    <Parameter Name="serviceId" Type="System.Int32" DbType="Int" />
    <ElementType Name="xspGetServiceMethodsResult">
      <Column Name="MethodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MethodKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceKey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MethodName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CachedResultLifetime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsResultCacheable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRestricted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLogged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspUpdateServiceMethod" Method="xspUpdateServiceMethod">
    <Parameter Name="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="serviceid" Type="System.Int32" DbType="Int" />
    <Parameter Name="methodkey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="methodname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cachedresultlifetime" Type="System.Int32" DbType="Int" />
    <Parameter Name="cacheresult" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="restricted" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="public" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="logged" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspExpireResultsCache" Method="xspExpireResultsCache">
    <Parameter Name="servicekey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="methodkey" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="itemcount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspGetRateLimitTypes" Method="xspGetRateLimitTypes">
    <ElementType Name="xspGetRateLimitTypesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspGetApplication" Method="xspGetApplication">
    <Parameter Name="apikey" Type="System.String" DbType="Char(36)" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="consumeriprange" Type="System.String" DbType="VarChar(31)" Direction="InOut" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Parameter Name="ratelimittypeid" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ratelimittype" Type="System.String" DbType="VarChar(50)" Direction="InOut" />
    <Parameter Name="ratelimit" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ratelimitinterval" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ispublic" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="islogged" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspGetApplicationList" Method="xspGetApplicationList">
    <ElementType Name="xspGetApplicationListResult">
      <Column Name="ApplicationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationKey" Type="System.String" DbType="Char(36)" CanBeNull="true" />
      <Column Name="ConsumerIPRange" Type="System.String" DbType="VarChar(31)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="RateLimitTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RateLimitType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RateLimit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RateLimitInterval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsPublic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLogged" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.xspUpdateApplication" Method="xspUpdateApplication">
    <Parameter Name="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="applicationName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="applicationKey" Type="System.String" DbType="Char(36)" />
    <Parameter Name="consumeriprange" Type="System.String" DbType="VarChar(31)" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="ratelimitid" Type="System.Int32" DbType="Int" />
    <Parameter Name="ratelimit" Type="System.Int32" DbType="Int" />
    <Parameter Name="ratelimitinterval" Type="System.Int32" DbType="Int" />
    <Parameter Name="public" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="logged" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspUpdateServiceSetting" Method="xspUpdateServiceSetting">
    <Parameter Name="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="serviceid" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="iv" Type="System.String" DbType="VarChar(64)" />
    <Parameter Name="value" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="tfEncrypted" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xspGetServiceSettings" Method="xspGetServiceSettings">
    <Parameter Name="servicekey" Type="System.String" DbType="Char(36)" />
    <Parameter Name="serviceid" Type="System.Int32" DbType="Int" />
    <Parameter Name="resultcode" Type="System.String" DbType="VarChar(10)" Direction="InOut" />
    <ElementType Name="xspGetServiceSettingsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IV" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="IsEncrypted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>